### ISSUE TITLE
Vue-google-mapを使った地図描画に置き換える

### ISSUE THREAD

**Issue by mark-n2** [shir0penk0/mog#26]
ブランチ: vue-gmap で作業中。

# とりあえずやってみたこと

* https://github.com/adalbueno/vue-mvvm-example を参考に、GoogleMapManagerのメソッドをVue.jsから読めるようにした
* 地図表示をvue-google-mapでやるようにした。mapcanvas等が不要になった

# 未実施

* DestinationManagerの処理が不十分

**Comment by shir0penk0** [comment]
実装完了
